### ISSUE TITLE
Error creating xml

### ISSUE THREAD

**Issue by KaidenTheo** [sebastianbergmann/phploc#207]
exec:
vendor/bin/phploc --log-xml phploc.xml src

Output:
Fatal error: Uncaught TypeError: DOMDocument::createElement() expects parameter 2 to be string, int given in /usr/local/www/secret/secret/vendor/phploc/phploc/src/Log/Xml.php:44
Stack trace:
#0 /usr/local/www/secret/secret/vendor/phploc/phploc/src/Log/Xml.php(44): DOMDocument->createElement('loc', 352)
#1 /usr/local/www/secret/secret/vendor/phploc/phploc/src/CLI/Command.php(122): SebastianBergmann\PHPLOC\Log\Xml->printResult('phploc.xml', Array)
#2 /usr/local/www/secret/secret/vendor/symfony/console/Command/Command.php(255): SebastianBergmann\PHPLOC\CLI\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/local/www/secret/secret/vendor/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/local/www/secret/secret/vendor/symfony/console/Applica in /usr/local/www/scarlettfm/http-request/vendor/phploc/phploc/src/Log/Xml.php on line 44

php --version:
PHP 7.4.3 (cli) (built: Feb 22 2020 01:14:30) ( NTS )

php --ini:
Configuration File (php.ini) Path: /usr/local/etc
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php
Additional .ini files parsed:      /usr/local/etc/php/ext-10-opcache.ini,
/usr/local/etc/php/ext-18-session.ini,
/usr/local/etc/php/ext-20-ctype.ini,
/usr/local/etc/php/ext-20-dom.ini,
/usr/local/etc/php/ext-20-fileinfo.ini,
/usr/local/etc/php/ext-20-filter.ini,
/usr/local/etc/php/ext-20-iconv.ini,
/usr/local/etc/php/ext-20-intl.ini,
/usr/local/etc/php/ext-20-json.ini,
/usr/local/etc/php/ext-20-mbstring.ini,
/usr/local/etc/php/ext-20-openssl.ini,
/usr/local/etc/php/ext-20-pdo.ini,
/usr/local/etc/php/ext-20-phar.ini,
/usr/local/etc/php/ext-20-posix.ini,
/usr/local/etc/php/ext-20-simplexml.ini,
/usr/local/etc/php/ext-20-sqlite3.ini,
/usr/local/etc/php/ext-20-tokenizer.ini,
/usr/local/etc/php/ext-20-xml.ini,
/usr/local/etc/php/ext-20-xmlreader.ini,
/usr/local/etc/php/ext-20-xmlwriter.ini,
/usr/local/etc/php/ext-20-zlib.ini,
/usr/local/etc/php/ext-30-pdo_sqlite.ini,
/usr/local/etc/php/ext-30-xsl.ini

cat composer.json:
{
    "name": "secret/secret",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "KaidenTheo",
            "email": "kaidentheo9@yandex.ru"
        }
    ],
    "minimum-stability": "stable",
    "autoload": {
        "psr-4": {
            "Secret\\Secret\\": "src/"
        }
    },
    "scripts": {
        "genDocs": "vendor/bin/phpdox -f phpdox.xml"
    },
    "require": {},
    "require-dev": {
        "theseer/phpdox": "^0.12.0",
        "phploc/phploc": "^6.0"
    }
}

composer --version:
Composer version 1.9.1 2019-11-01 17:20:17

uname -a:
FreeBSD backendmd 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

**Comment by KaidenTheo** [comment]
May be strict types crash your lib
